blank_issues_enabled: false
contact_links:
  - name: 锔 Servidor de Contribuci贸n
    url: https://discord.gg/2jJRNbyqMB
    about: Entra al servidor de contribuci贸n e inf贸rmate con lo que necesites
  - name:  Servidor Principal
    url: https://discord.gg/doofy-s-projects-704042607600205956
    about: Asegurate de leer la informaci贸n del servidor